on:
  workflow_call:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - run: npm install --omit=dev
      - run: npm run build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      - uses: actions/deploy-pages@v4

