on:
  workflow_call:
jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec brakeman --no-pager
